archivo = open('parrafo.txt', 'w')
archivo.write("caldo de pollo con tamales.\n")
archivo.write("pamvaso con chirmole.\n")
archivo.write("tortillas o tostadas tu decides\n")
archivo.write("aqui de esperamos en pollos asados curri")
archivo.close()
archivo = open('parrafo.txt', 'r')
lineas = archivo.readlines()
archivo.close()
cantidad = len(lineas)
print(f"El archivo tiene {cantidad} líneas.")
