requisito1 = input ("¿Cuál es tu nombre?")
requisito2 = input ("¿Cuál es tu segundo nombre?")
requisito3 = input ("¿Cuál es tu apellido paterno?")
requisito4 = input ("¿Cuál es tu apellido materno?")
print ("Tu nombre es", requisito1, requisito2, requisito3, requisito4)