archivo = open("parrafo.txt", "w")
archivo.write("Eso tilin.\n")
archivo.write("wow tilin.\n")
archivo.write("ala tilin.\n")
archivo.close()
archivo_lectura = open("parrafo.txt", "r")
lineas = archivo_lectura.readlines()
archivo_lectura.close()
numero_de_lineas = len(lineas)
print(f"El archivo tiene {numero_de_lineas} líneas.")