oracion = input("Ingresa una oración: ")
print( )
print(oracion)
print( )
h1 = input("Ingresa la palabra que deseas reemplazar: ")
print()
h2 = input("Ingrese la nueva palabra: ")
print( )
h3 = oracion.replace(h1, h2)
print(h3)