archivo = open("texto.txt", "w")
archivo.write('hola que tal tu dia de hoy')
archivo.close()
palabra = input("Introduce la palabra que deseas buscar: ").lower()
archivo = open("texto.txt", "r")
contenido = archivo.read().lower()
archivo.close()
apariciones = contenido.count(palabra)
print(f"La palabra '{palabra}' aparece {apariciones} veces.")