archivo = open('parrafo.txt', 'w')
archivo.write("when haces un momo en ciencia de datos.\n")
archivo.write("el futuro es hoy oiste viejo.\n")
archivo.write("but te terminan reprobando.\n")
archivo.write("ohhh mi lente de contacto xdxddxdxx")
archivo.close()
archivo = open('parrafo.txt', 'r')
lineas = archivo.readlines()
archivo.close()
cantidad = len(lineas)
print(f"El archivo tiene {cantidad} líneas.")
